export const PLATFORMS = [
  {
    id: 'youtube',
    name: 'YouTube',
    tagline: '4K / PLAYLISTS',
    icon: 'smart_display',
    route: '/youtube',
    badge: '4K UHD // 60FPS',
    color: 'var(--color-primary-container)',
    accentColor: 'var(--color-primary)',
    placeholder: 'Paste YouTube video or playlist URL (e.g., https://youtube.com/watch?v=... or /playlist?list=...)',
    defaultUrl: 'https://youtube.com/playlist?list=PL_SOLARIS_EXPEDITION_4K',
    formats: [
      { id: 'mp4', label: 'MP4', badge: '4K UHD', desc: '2160p Master HEVC', type: 'video' },
      { id: 'webm', label: 'WEBM', badge: 'AV1 CODEC', desc: 'High Efficiency Master', type: 'video' },
      { id: 'mp3', label: 'MP3', badge: '320 KBPS', desc: 'Constant Bitrate HQ', type: 'audio' },
      { id: 'wav', label: 'WAV', badge: '96 KHZ', desc: 'Lossless Uncompressed', type: 'audio' },
      { id: 'm4a', label: 'M4A', badge: 'AAC 256K', desc: 'Apple Spatial Pristine', type: 'audio' },
      { id: 'zip', label: 'ZIP', badge: 'ALL-IN-1', desc: 'Batch Harvest Archive', type: 'archive' },
    ],
    defaultFormat: 'mp4',
    sampleMedia: {
      title: 'Solaris_Cinematic_Audio_Session_Ep4.mp4',
      duration: '04:32',
      resolution: '3840×2160',
      fps: '59.94',
      bitrate: '18.4 MBPS',
      size: '284.6 MB',
      codec: 'HEVC / H.265 MAIN 10',
      audioCodec: 'AAC LC / DUAL STEREO',
      colorGamut: 'DCI-P3 HDR10 PROFILE'
    }
  },
  {
    id: 'spotify',
    name: 'Spotify',
    tagline: 'TRACKS & ALBUMS',
    icon: 'music_note',
    route: '/spotify',
    badge: 'LOSSLESS 24-BIT',
    color: '#1DB954',
    accentColor: '#1ed760',
    placeholder: 'Paste Spotify track, album, or playlist URL (e.g., https://open.spotify.com/album/...)',
    defaultUrl: 'https://open.spotify.com/album/4aawyAB9vmqN3uQ7FjRGTy',
    formats: [
      { id: 'mp3', label: 'MP3', badge: '320 KBPS', desc: 'ID3v2 Tagged HQ', type: 'audio' },
      { id: 'flac', label: 'FLAC', badge: '24-BIT', desc: 'Lossless Studio Master', type: 'audio' },
      { id: 'wav', label: 'WAV', badge: '96 KHZ', desc: 'PCM Uncompressed', type: 'audio' },
      { id: 'm4a', label: 'M4A', badge: 'AAC 320K', desc: 'Apple Music Spec', type: 'audio' },
      { id: 'zip', label: 'ZIP', badge: 'ALBUM ZIP', desc: 'Complete Album Bundle', type: 'archive' },
    ],
    defaultFormat: 'mp3',
    sampleMedia: {
      title: 'Late Night Sessions Vol. IV (Original Audio Master)',
      duration: '48:16',
      resolution: 'N/A (Pure Audio)',
      fps: 'N/A',
      bitrate: '1,411 KBPS LOSSLESS',
      size: '248.4 MB',
      codec: 'FLAC 24-BIT / 48.0 KHZ',
      audioCodec: 'STEREO PCM HIGH PROFILE',
      colorGamut: 'EMBEDDED COVER ART 3000x3000'
    }
  },
  {
    id: 'vimeo',
    name: 'Vimeo Pro',
    tagline: 'DCI 4K RAW',
    icon: 'movie',
    route: '/youtube', // or general downloader
    badge: 'PRORES 422',
    color: 'var(--color-secondary)',
    accentColor: 'var(--color-secondary)',
    placeholder: 'Paste Vimeo showcase or video link (e.g., https://vimeo.com/...)',
    defaultUrl: 'https://vimeo.com/channels/staffpicks/89274819',
    formats: [
      { id: 'mp4', label: 'MP4', badge: '4K DCI', desc: 'ProRes / HEVC Stream', type: 'video' },
      { id: 'webm', label: 'WEBM', badge: 'VP9 HQ', desc: 'Original Container', type: 'video' },
      { id: 'wav', label: 'WAV', badge: '24-BIT', desc: '5.1 Surround Stems', type: 'audio' },
      { id: 'zip', label: 'ZIP', badge: 'PROJECT', desc: 'Video + Stem Bundle', type: 'archive' },
    ],
    defaultFormat: 'mp4',
    sampleMedia: {
      title: 'Canyon_Erosion_Documentary_Master_Cut.mp4',
      duration: '12:40',
      resolution: '4096×2160',
      fps: '24.00 DCI',
      bitrate: '42.0 MBPS',
      size: '3.8 GB',
      codec: 'Apple ProRes 422 HQ',
      audioCodec: 'Linear PCM 24-bit 48kHz',
      colorGamut: 'Apple Log / DCI-P3 Wide'
    }
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud',
    tagline: 'LOSSLESS FLAC',
    icon: 'graphic_eq',
    route: '/spotify',
    badge: 'HQ AUDIO',
    color: 'var(--color-tertiary)',
    accentColor: 'var(--color-tertiary)',
    placeholder: 'Paste SoundCloud track or set URL (e.g., https://soundcloud.com/...)',
    defaultUrl: 'https://soundcloud.com/artist/deep-space-odyssey-set',
    formats: [
      { id: 'flac', label: 'FLAC', badge: 'ORIGINAL', desc: 'Lossless Studio Master', type: 'audio' },
      { id: 'mp3', label: 'MP3', badge: '320 KBPS', desc: 'High Definition CBR', type: 'audio' },
      { id: 'wav', label: 'WAV', badge: '96 KHZ', desc: 'PCM Waveform Stems', type: 'audio' },
    ],
    defaultFormat: 'flac',
    sampleMedia: {
      title: 'Hyperdrive_Live_Modular_Set_Berlin.flac',
      duration: '64:20',
      resolution: 'Audio Stems',
      fps: 'N/A',
      bitrate: '2,116 KBPS FLAC',
      size: '680.2 MB',
      codec: 'FLAC 24-BIT / 96.0 KHZ',
      audioCodec: 'Direct Soundboard Master',
      colorGamut: 'Spectrogram Verified'
    }
  },
  {
    id: 'x',
    name: 'X / Media',
    tagline: 'VIDEO CLIPS',
    icon: 'alternate_email',
    route: '/youtube',
    badge: 'H.264 HD',
    color: 'var(--color-outline)',
    accentColor: 'var(--color-on-surface)',
    placeholder: 'Paste X / Twitter post URL containing video (e.g., https://x.com/user/status/...)',
    defaultUrl: 'https://x.com/MediaForgeEng/status/178920194829',
    formats: [
      { id: 'mp4', label: 'MP4', badge: '1080P', desc: 'High Quality Clip', type: 'video' },
      { id: 'mp3', label: 'MP3', badge: 'VOICE', desc: 'Speech Extractor', type: 'audio' },
      { id: 'gif', label: 'GIF', badge: '60 FPS', desc: 'Looping Master', type: 'video' },
    ],
    defaultFormat: 'mp4',
    sampleMedia: {
      title: 'SpaceX_Starship_Orbital_Egress_Capture.mp4',
      duration: '01:14',
      resolution: '1920×1080',
      fps: '60.00',
      bitrate: '8.2 MBPS',
      size: '72.4 MB',
      codec: 'H.264 High Profile',
      audioCodec: 'AAC 192 KBPS',
      colorGamut: 'Rec.709 Standard'
    }
  },
  {
    id: 'direct',
    name: 'Direct Stream',
    tagline: 'HLS / M3U8',
    icon: 'link',
    route: '/youtube',
    badge: 'RAW STREAM',
    color: 'var(--color-secondary)',
    accentColor: 'var(--color-secondary)',
    placeholder: 'Paste direct streaming manifest (e.g., .m3u8, .mpd, .mp4 link)',
    defaultUrl: 'https://stream.mediaforge.internal/live/master.m3u8',
    formats: [
      { id: 'mp4', label: 'MP4', badge: 'REMUX', desc: 'Lossless Container Wrap', type: 'video' },
      { id: 'mkv', label: 'MKV', badge: 'ALL TRACKS', desc: 'Multi-Audio Multi-Sub', type: 'video' },
      { id: 'ts', label: 'TS', badge: 'RAW DUMP', desc: 'Original Stream Segments', type: 'video' },
    ],
    defaultFormat: 'mp4',
    sampleMedia: {
      title: 'Broadband_Edge_Relay_Channel_09.mp4',
      duration: 'Live Stream',
      resolution: '3840×2160',
      fps: '59.94',
      bitrate: '22.0 MBPS',
      size: 'Dynamic Buffer',
      codec: 'AV1 + Opus Ingest',
      audioCodec: 'Dual Channel Opus 48kHz',
      colorGamut: 'BT.2020 Dynamic'
    }
  }
];

export const MOCK_DOWNLOADS_HISTORY = [
  {
    id: 'MF-8921',
    title: 'Solaris_Cinematic_Audio_Session_Ep4.mp4',
    platform: 'YouTube',
    platformId: 'youtube',
    format: 'MP4',
    quality: '4K UHD (2160p @ 60fps)',
    duration: '04:32',
    size: '284.6 MB',
    status: 'Completed',
    date: '2026-09-08 11:45',
    progress: 100,
    bitrate: '18.4 Mbps',
    codec: 'HEVC / H.265'
  },
  {
    id: 'MF-8920',
    title: 'Late Night Sessions Vol. IV (Original Audio Master).zip',
    platform: 'Spotify',
    platformId: 'spotify',
    format: 'ZIP (12 FLACs)',
    quality: 'Lossless 24-bit / 48kHz',
    duration: '48:16',
    size: '248.4 MB',
    status: 'Completed',
    date: '2026-09-08 11:12',
    progress: 100,
    bitrate: '1,411 kbps',
    codec: 'FLAC'
  },
  {
    id: 'MF-8919',
    title: 'Canyon_Erosion_Documentary_Master_Cut.mp4',
    platform: 'Vimeo Pro',
    platformId: 'vimeo',
    format: 'MP4',
    quality: 'DCI 4K RAW (4096p)',
    duration: '12:40',
    size: '3.8 GB',
    status: 'Completed',
    date: '2026-09-08 09:30',
    progress: 100,
    bitrate: '42.0 Mbps',
    codec: 'ProRes 422 HQ'
  },
  {
    id: 'MF-8918',
    title: 'Stellar_Horizon_Ambient_Mix.wav',
    platform: 'SoundCloud',
    platformId: 'soundcloud',
    format: 'WAV',
    quality: '96 kHz / 24-bit Studio',
    duration: '04:12',
    size: '69.4 MB',
    status: 'Processing',
    date: '2026-09-08 12:02',
    progress: 68,
    bitrate: '2,304 kbps',
    codec: 'Linear PCM'
  },
  {
    id: 'MF-8917',
    title: 'Deep_Frequency_Resonance_Stem_Pack.zip',
    platform: 'Spotify',
    platformId: 'spotify',
    format: 'ZIP',
    quality: 'Multitrack Stems (4 Stems)',
    duration: '03:59',
    size: '142.1 MB',
    status: 'Queued',
    date: '2026-09-08 12:10',
    progress: 0,
    bitrate: 'Lossless',
    codec: 'FLAC'
  }
];
